### ISSUE TITLE
Mid-point review

### ISSUE THREAD

**Issue by garethfuller** [michaelecolley/jerrycan#5]
Nice work so far! 🙌 

A few comments and suggestions for improvements:

1. The naming [here](https://github.com/michaelecolley/jerrycan/blob/main/src/gas-price-service.ts#L15) could be simpler, just `blocknativeApiKey` would do.
2. Given that we might need more constructor options [here](https://github.com/michaelecolley/jerrycan/blob/main/src/gas-price-service.ts#L15) in the future (and for readability as a dev working with the package), how could we better structure the options passed into the constructor?
3. `configService` is a confusing input name [here](https://github.com/michaelecolley/jerrycan/blob/main/src/gas-price-service.ts#L22), I guess it's been copied from our codebase. It should probably be `provider?`.
4. Given that the input to [this function](https://github.com/michaelecolley/jerrycan/blob/main/src/gas-price-service.ts#L22-L36) is a provider and a provider is not necessarily tied to a specific network, how could we better structure this function to allow for both a `provider` input and a `network` input?. Additionally, I think enums should be used.
5. Given that `blocknativeApiKey` is an optional constructor argument we should throw an exemption if `getLatest` is called for that provider and the API key doesn't exist.
6. Further, we should remove the dotenv dependency and if the user does not provide the blocknative api key in the constructor the provider should not be available.

👏 Kudos:
1. Love the name
2. Love the documentation
2. Tests

**Comment by michaelecolley** [comment]
Thanks for the feedback Gareth! This is really great. I had initially thought to both embed the `process.env` dependencies (for Balancer's use case) and also have the user facing inputs so that a user can input their own data but that said I agree that the implementation would be far easier to reason about. 

Agreed on the naming conventions. My reasoning behind why I thought it made sense for us to use both enums and string input was again due to me trying to bridge the balancer frontend and average user use cases (via plain text). Although after some additional research I can see that the enums correspond to Chain Ids. I hadn't realised this and so will stick to following that pattern!

**Comment by michaelecolley** [comment]
Just to loop round and clarify something you mentioned:

`Given that we might need more constructor options here in the future (and for readability as a dev working with the package), how could we better structure the options passed into the constructor?`

My current thinking is that actually breaking it out in a more long form - while being relatively verbose might be easier to reason about for incoming devs. By the comment you made above did you mean to suggest the same in line with the pattern below 👇 

```
// frontend-v2 > src > lib > utils > balancer > contracts.ts
export class Multicaller {
  public network: string;
  public provider: JsonRpcProvider;
  public abi: any[];
  public options: any = {};
  public calls: any[] = [];
  public paths: any[] = [];

  constructor(
    network: string,
    provider: JsonRpcProvider,
    abi: any[],
    options?
  ) {
    this.network = network;
    this.provider = provider;
    this.abi = abi;
    this.options = options || {};
  }

```

As opposed to:

```
export default class GasPriceService {
  constructor(
    private providerApiKey?: string,
    private readonly blocknativeProvider = new BlocknativeProvider(
      providerApiKey
    ),
    private readonly polygonProvider = new PolygonProvider()
  ) {}
```

**Comment by garethfuller** [comment]
Hey, this isn't really what I was suggesting, I was more looking for a typed options object that included `providerApiKey` as an optional param. 

An implementation like [this](https://www.typescriptlang.org/play?#code/C4TwDgpgBACghgJzgWwM5QLxQN5UQcwEYB+ALilWAQEsA7fKAHyloFcAbdgbjwXwCYyFKnQbM2nKAF8uAWABQ7CMChhEKVOXhI0mHDIUKAZq1oBjYNQD2tKMhAAxU2YAU2AoQwT2AGgL8vDnYpPTUdVABKbAUoWN4iKGIoMxtUKyUAOnYrfBcAcg88ADc4anY4ACMlPJ94wgiochTaNMzs3IK+QhYrFTgSssqlWoALOFoAEyUoYBHqVDyIuXk4+P5E5NT0iCyc-P9i0vKqiBq1hqattr3OgR6+gePhqDHJ6dn5xeWpQ3l7J3Mbjq5DyaWQEAA0hAQHlpEsgA) could work well here. Where `myFunc` is the constructor and the params object would be the first argument. The blocknative/polygon provider arguments can stay as they are.

Apart from it's flexibility this approach also makes the interface more understandable for the end user. Consider the usage of the two implementations:
```ts
const gasPrice = new GasPriceService('asdasfdsfadwdkqwdsomeRandomApiKeyString', 'asdasfdsfadwdkqwdsomeOtherRandomApiKeyString')

// or

const blocknativeApiKey = 'asdasfdsfadwdkqwdsomeRandomApiKeyString'
const anotherApiKey = 'asdasfdsfadwdkqwdsomeOtherRandomApiKeyString'

const gasPrice = new gasPriceService({ blocknativeApiKey, anotherApiKey })
```
Although the second implementation is more lines of code, it's far easier to understand what's going on.

**Comment by michaelecolley** [comment]
Hey @garethfuller I've updated the repo with the comments and suggestions you made. The link to the PR is above. I'm not sure how this typically works with take home tasks but to clarify my position on this - I would usually 100% get you to review the PR ahead of merging. Since this is a hybrid open source/take home task I made the call that we'd work in this particular way - shipping and then reviewing post merge. 

On reflection I think I should've asked you upfront since this is obviously a test to see how we might work together. This may be worth clarifying for future interviews you host. 

As an aside I thoroughly enjoyed working on this take home task. It was literally the best one I've worked on and I learned a thing or two from your feedback so thanks! 🙌

I look forward to receiving your feedback on this iteration of the project, let me know if you want me to copy this repo anywhere in particular or if there are any additional steps after this 🚀
